"""add url for vuz

Revision ID: 4c10d76d655d
Revises: 74dd95f12a48
Create Date: 2026-04-08 00:43:24.027109

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c10d76d655d"
down_revision: Union[str, Sequence[str], None] = "74dd95f12a48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vuzopedia_program", sa.Column("url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vuzopedia_program", "url")
    # ### end Alembic commands ###
