"""add cities

Revision ID: 74dd95f12a48
Revises: d5fa9c7e61c3
Create Date: 2026-04-08 00:38:28.290906

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74dd95f12a48"
down_revision: Union[str, Sequence[str], None] = "d5fa9c7e61c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_city_id"), "city", ["id"], unique=False)
    op.create_table(
        "city_vuzopedia_program",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("vuzopedia_program_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vuzopedia_program_id"],
            ["vuzopedia_program.id"],
        ),
        sa.PrimaryKeyConstraint("city_id", "vuzopedia_program_id"),
    )
    op.add_column("vuzopedia_program", sa.Column("paid_places", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vuzopedia_program", "paid_places")
    op.drop_table("city_vuzopedia_program")
    op.drop_index(op.f("ix_city_id"), table_name="city")
    op.drop_table("city")
    # ### end Alembic commands ###
