"""Initial tables

Revision ID: c796818c4fae
Revises:
Create Date: 2026-01-31 21:29:34.633339

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c796818c4fae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hse_program",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("study_type", sa.String(length=50), nullable=True),
        sa.Column("budget_places", sa.Integer(), nullable=True),
        sa.Column("paid_places", sa.Integer(), nullable=True),
        sa.Column("foreigners_places", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hse_program_id"), "hse_program", ["id"], unique=False)
    op.create_table(
        "vuzopedia_program",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("study_type", sa.String(length=50), nullable=True),
        sa.Column("min_budget_score", sa.Integer(), nullable=True),
        sa.Column("min_paid_score", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("sphere", sa.Text(), nullable=True),
        sa.Column("career_prospects", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vuzopedia_program_id"), "vuzopedia_program", ["id"], unique=False)
    op.create_table(
        "hse_course",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("module", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("track", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("results", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("credits", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["hse_program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hse_course_id"), "hse_course", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hse_course_id"), table_name="hse_course")
    op.drop_table("hse_course")
    op.drop_index(op.f("ix_vuzopedia_program_id"), table_name="vuzopedia_program")
    op.drop_table("vuzopedia_program")
    op.drop_index(op.f("ix_hse_program_id"), table_name="hse_program")
    op.drop_table("hse_program")
    # ### end Alembic commands ###
