"""delete_track_field

Revision ID: d5fa9c7e61c3
Revises: e6bb591193d3
Create Date: 2026-03-16 14:44:51.216401

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5fa9c7e61c3"
down_revision: Union[str, Sequence[str], None] = "e6bb591193d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hse_course", "track")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hse_course", sa.Column("track", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
