"""Update models to match CSV structure

Revision ID: e6bb591193d3
Revises: c796818c4fae
Create Date: 2026-03-11 13:13:59.369360

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6bb591193d3"
down_revision: Union[str, Sequence[str], None] = "c796818c4fae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hse_course", sa.Column("url", sa.Text(), nullable=True))
    op.alter_column(
        "hse_course",
        "year",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "hse_course",
        "credits",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.add_column("hse_program", sa.Column("url", sa.Text(), nullable=True))
    op.add_column("vuzopedia_program", sa.Column("budget_places", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vuzopedia_program", "budget_places")
    op.drop_column("hse_program", "url")
    op.alter_column(
        "hse_course",
        "credits",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "hse_course",
        "year",
        existing_type=sa.String(length=50),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("hse_course", "url")
    # ### end Alembic commands ###
