#FROM postgres:15-alpine
#WORKDIR /app
#
#COPY init.sql /docker-entrypoint-initdb.d/
#
#RUN chmod a+r /docker-entrypoint-initdb.d/*
#
#ENV POSTGRES_USER=edu_user
#ENV POSTGRES_PASSWORD=edu_password
#ENV POSTGRES_DB=edu_analytics
#
#EXPOSE 5432
#
#CMD ["postgres"]
